[package]
name = "rs-vpsman"
version = "0.1.0"
authors = ["linuxing3 <linuxing3@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
iced = "0.2"
