name: rs-vpsman
version: "1.0"
author: linuxing3<linuxing3@gmail.com>
about: Manage my vps
args:
    - config:
        short: c
        long: config
        value_name: FILE
        about: Sets a custom config file
        takes_value: true
    - INPUT:
        about: Sets the input file to use
        required: true
        index: 1
    - verbose:
        short: v
        multiple: true
        about: Sets the level of verbosity
subcommands:
    - gui:
        about: open gui
        version: "1.3"
        author: linuxing3<linuxing3@gmail.com>
        args:
            - g:
                short: g
    - connect:
        about: Connect to vps server
        version: "1.3"
        author: linuxing3<linuxing3@gmail.com>
        args:
            - host:
                short: h
                long: host
                value_name: HOST
                about: Input the host name or address
                takes_value: true