name: vpsman
version: "1.0"
author: linuxing3<linuxing3@gmail.com>
about: Manage my vps
settings:
    - ArgRequiredElseHelp

args:
    - mode:
        long: mode
        help: shows an option with specific values
        possible_values: [ vi, emacs ]
        takes_value: true

subcommands:
    - gui:
        about: open gui
        version: "1.3"
        author: linuxing3<linuxing3@gmail.com>
        args:
            - g:
                short: g
    - connect:
        about: Connect to vps server
        version: "1.3"
        author: linuxing3<linuxing3@gmail.com>
        args:
            - host:
                short: h
                long: host
                value_name: HOST
                about: Input the host name or address
                takes_value: true